modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mrthomas20121/WoodDeco/issues"

[[mods]]
modId = "wood_deco"
version = "1.20.1-1.0.0"
displayName = "Wood Deco"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/wood-deco"
#logoFile="tinkers_reforged_logo.png"
#credits = ""
authors = "Mrthomas20121"
description = '''
Add new wood decorative blocks to minecraft.
'''

[[dependencies.wood_deco]]
    modId = "forge"
    mandatory = true
    versionRange = "[0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.wood_deco]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[0,)"
    ordering = "NONE"
    side = "BOTH"